name: just_mobile
description: "just."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14
  flutter_feather_icons: ^2.0.0+1
  get:




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Thin.otf
        - asset: assets/fonts/Pretendard-ExtraLight.otf
        - asset: assets/fonts/Pretendard-Light.otf
        - asset: assets/fonts/Pretendard-Medium.otf
        - asset: assets/fonts/Pretendard-ExtraBold.otf
    - family: Ydestreet
      fonts:
        - asset: assets/fonts/YdestreetB.otf
        - asset: assets/fonts/YdestreetL.otf
  assets:
    - assets/images/logo.png
    - assets/images/pr.png
    - assets/images/tube.png
    - assets/images/cr.png
    - assets/images/pr2.png
    - assets/images/file.png
    - assets/images/star.png
    - assets/images/c1.png
    - assets/images/c2.png
    - assets/images/c3.png
    - assets/images/you.png
    - assets/images/lie.png
